version: 2.1
jobs:
  Java SE 8 Maven Verify:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Generate cache checksum
          command: cat pom.xml */pom.xml > allpoms.xml
      - restore_cache:
          key: maven-{{ checksum "allpoms.xml" }}
      - run:
          name: Install dependencies
          command: ./mvnw --settings settings-ci.xml --batch-mode dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2/
          key: maven-{{ checksum "allpoms.xml" }}
      - run:
          name: Compile, test, verify
          command: ./mvnw --settings settings-ci.xml --batch-mode verify
      - run:
          name: Collect test results
          command: |
            mkdir -p ~/test-results/JUnit/
            find . -type f -regex '.*/target/surefire-reports/.*\.xml' -exec cp {} ~/test-results/JUnit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  version: 2
  Build and Test:
    jobs:
      - Java SE 8 Maven Verify
